### ISSUE TITLE
Plugin isn't working for me

### ISSUE THREAD

**Issue by SyncPerfect** [syntaxjedi/RuinsLoot#1]
Hi! I posted on bukkit and you told me to go here.

Plugin version: 0.2.2
Server version: 1.12

I can find the plugin commands using /help, but none of the commands actually work.
So, the installation went without errors, but at the very moment the server is started (done loading plugins), this happens: 

> 18.11 00:59:26 [Server] INFO at net.syntaxjedi.ruinsloot.RuinsLoot.onChunkLoadEvent(RuinsLoot.java:167) ~[?:?]
18.11 00:59:26 [Server] INFO at net.syntaxjedi.ruinsloot.RuinsLoot.findChest(RuinsLoot.java:174) ~[?:?]
18.11 00:59:26 [Server] INFO Caused by: java.lang.NullPointerException
18.11 00:59:26 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:742) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:304) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:750) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.BlockFire.b(BlockFire.java:152) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.BlockFire.a(BlockFire.java:235) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.World.getType(World.java:767) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.World.getChunkAtWorldCoords(World.java:290) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.World.getChunkAt(World.java:294) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:51) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:852) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:498) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:26 [Server] INFO org.bukkit.event.EventException: null
18.11 00:59:26 [Server] ERROR Could not pass event ChunkLoadEvent to RuinsLoot v0.2.2
18.11 00:59:26 [Multicraft] Skipped 7 lines due to rate limit (30/s)
18.11 00:59:25 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:690) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:25 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:25 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-beta3-os.jar:git-Bukkit-9a1f5ee]
18.11 00:59:25 [Server] INFO at net.syntaxjedi.ruinsloot.RuinsLoot$1.run(RuinsLoot.java:60) ~[?:?]
18.11 00:59:25 [Server] INFO at net.syntaxjedi.ruinsloot.RuinsLoot.findChest(RuinsLoot.java:174) ~[?:?]
18.11 00:59:25 [Server] INFO java.lang.NullPointerException: null
18.11 00:59:25 [Server] WARN Task #6 for RuinsLoot v0.2.2 generated an exception
18.11 00:59:25 [Server] Startup Done (12.303s)! For help, type "help" or "?"

**Comment by syntaxjedi** [comment]
The error has been fixed, please download the latest version of the plugin from
[Spigot](https://www.spigotmc.org/resources/ruins-loot.49475/) or
[Bukkit](https://dev.bukkit.org/projects/ruins-loot)
